---

- name: Add node to kubernetes cluster
  gather_facts: false
  hosts: all
  tasks:
    - name: Copy script
      copy: src=/root/abench/addnode dest=/home/user/addnode mode=0777

    - name: Add node to cluster
      ansible.builtin.shell: sh /home/user/addnode
      become: yes
